services:
  back:
    build: ./backend_api/
    depends_on:
      - ${mysqlHost}
    command: sh -c "sleep 10s ; python3 ./app.py"
    environment:
      - mysqlDb=${mysqlDb}
      - mysqlUn=${mysqlUn}
      - mysqlRp=${mysqlRp}
      - mysqlPort=${mysqlPort}
      - mysqlHost=${mysqlHost}
      - port=${port}
      - host=${host}
    ports:
      - '${port}:${port}'
  mysql:
    build: ./db_config/
    restart: always
    environment:
      MYSQL_DATABASE: ${mysqlDb}
      MYSQL_ROOT_PASSWORD: ${mysqlRp}
    ports:
      - '${mysqlPort}:${mysqlPort}'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - ${mysqlHost}
    environment:
      PMA_HOST: ${mysqlHost}
      MYSQL_ROOT_PASSWORD: ${mysqlRp}
    ports:
      - '${phpPort}'